# Generated by Django 5.1.1 on 2024-09-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение товара",
                null=True,
                upload_to="catalog/preview",
                verbose_name="Изображение",
            ),
        ),
    ]
