# Generated by Django 5.1.1 on 2024-10-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name", "price", "created_at", "updated_at", "category"),
                "permissions": [
                    ("can_set_published", "Can set published"),
                    ("can_edit_product_description", "Can edit description"),
                    ("can_edit_category_product", "Can edit category"),
                ],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Отметить для публикации",
                verbose_name="Опубликовано",
            ),
        ),
    ]
